### ISSUE TITLE
Link relation registration

### ISSUE THREAD

**Issue by mnot** [dewitt/opensearch#43]
[ wearing my IANA link relation registry expert hat]

Hello,

The [IANA link relation registry](https://www.iana.org/assignments/link-relations/link-relations.xhtml) has an entry for `search` that references `http://www.opensearch.org/Specifications/OpenSearch/1.1`.

Following that link currently results in a `404`, and that Web site now appears to be used for an unrelated search project.

I've contacted the Amazon OpenSearch folks, who pointed me to this repo as authoritative for the link relation.

Could you please confirm this, and provide an updated link for the purposes of the registration?

Thank you,

(tracking in <https://github.com/protocol-registries/link-relations/issues/48>)

**Comment by dewitt** [comment]
Thanks for the report, @mnot!

Yes, this is accurate. Amazon, who controls the opensearch.org domain that originally hosted these specifications, [repurposed the brand name and domain](https://opensearch.org/disambiguation.html) for an unrelated technology.

The best canonical link now for the specifications is now this site: `https://github.com/dewitt/opensearch`

This link is admittedly not ideal, since there are now two potential points of failure: First, `github.com` is controlled by a single company. And `dewitt/opensearch` is controlled by a single individual. Both are relatively stable, but as we've seen, anything can change.

I don't have a better recommendation however, as the link relation is in wide-enough use that removing it from the registry doesn't seem like a good idea either. So I'm okay with updating the link relation to point to the above URL if need be.

What do you suggest?

**Comment by mnot** [comment]
A github link with a single owner is not ideal, and we usually discourage it. However I think we can grandfather it in here. I'll update the entry accordingly -- thanks!
